  curl 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3' \
  -H 'authority: api.thegraph.com' \
  -H 'accept: application/json, multipart/mixed' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'content-type: application/json' \
  -H 'origin: https://api.thegraph.com' \
  -H 'referer: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3/graphql?query=query+MyQuery+%7B%0A++token%28id%3A+%220x171b1daefac13a0a3524fcb6beddc7b31e58e079%22%29+%7B%0A++++decimals%0A++++derivedETH%0A++++feesUSD%0A++++id%0A++++name%0A++++symbol%0A++++totalSupply%0A++++totalValueLocked%0A++++totalValueLockedUSD%0A++++totalValueLockedUSDUntracked%0A++++txCount%0A++%7D%0A++transactions%28%0A++++where%3A+%7Bswaps_%3A+%7Btoken0%3A%220x171b1daefac13a0a3524fcb6beddc7b31e58e079%22%7D%7D%0A++%29+%7B%0A++++blockNumber%0A++++timestamp%0A++++id%0A++++gasUsed%0A++++gasPrice%0A++++swaps+%7B%0A++++++id%0A++++++amount0%0A++++++amount1%0A++++++token0+%7B%0A++++++++id%0A++++++++name%0A++++++++symbol%0A++++++%7D%0A++++++token1+%7B%0A++++++++decimals%0A++++++++id%0A++++++++name%0A++++++++symbol%0A++++++%7D%0A++++++transaction+%7B%0A++++++++swaps+%7B%0A++++++++++amount0%0A++++++++++amount1%0A++++++++++token0+%7B%0A++++++++++++id%0A++++++++++++name%0A++++++++++%7D%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%0A%7D' \
  -H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  --data '{"query":"query MyQuery {\n  token(id: \"0x171b1daefac13a0a3524fcb6beddc7b31e58e079\") {\n    decimals\n    derivedETH\n    feesUSD\n    id\n    name\n    symbol\n    totalSupply\n    totalValueLocked\n    totalValueLockedUSD\n    totalValueLockedUSDUntracked\n    txCount\n  }\n  transactions(\n    where: {swaps_: {token0: \"0x171b1daefac13a0a3524fcb6beddc7b31e58e079\"}}\n  ) {\n    blockNumber\n    timestamp\n    id\n    gasUsed\n    gasPrice\n    swaps {\n      id\n      amount0\n      amount1\n      token0 {\n        id\n        name\n        symbol\n      }\n      token1 {\n        decimals\n        id\n        name\n        symbol\n      }\n      transaction {\n        swaps {\n          amount0\n          amount1\n          token0 {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}","variables":null,"extensions":{"headers":null}}' \
  --compressed