# The class cannot be named by Pascal or camel case.
# The class cannot be named by Pascal or camel case.
# If it is not used, the corresponding structure will not be set,
# and it will not be read naturally.
serverversion: 2.0.0
#---------------BlockchainData configuration---------------------#
redis:
  # dbAddress: [ 127.0.0.1:6379 ] #本地
  # dbAddress: [ 3.0.175.230:46379 ] #测试环境
  dbAddress: [ blockchaindata.ad9n4e.clustercfg.apse1.cache.amazonaws.com:6379 ] #生产环境
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbPassWord: #redis密码 建议修改
  enableCluster: true #如果外部redis以集群方式启动，需要打开此开关
